spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpa_tutorial
    username: root
    password: anilsa3omsa
  jpa:
    hibernate:
      ddl-auto: create-drop
#      ddl-auto: update
    database: mysql
    show-sql: true